<?php
$listing_proprietes = array(

	'z-index',
	
	'position',
	
	'display',
	
	'float',
	
	'width',   		
	'height',
	
	'top',
	'right',
	'bottom',
	'left',
	
	'margin',
	'margin-bottom',
	'margin-left',
	'margin-right',
	'margin-top',
	
	'padding',
	'padding-bottom',
	'padding-left',
	'padding-right',
	'padding-top',
	
	'overflow',
	
	'azimuth',
	'caption-side',
	'clear',
	'clip',
	'content',
	'counter-increment',
	'counter-reset',
	'cursor',
	'direction',
	'empty-cells',
	'letter-spacing',
	'list-style',
	'list-style-image',
	'list-style-position',
	'list-style-type',

	'max-height',
	'max-width',
	'min-height',
	'min-width',
	'orphans',
	'page-break-after',
	'page-break-before',
	'page-break-inside',
	'quotes',
	'table-layout',
	'text-align',
	'text-decoration',
	'text-indent',
	'text-shadow',
	'text-transform',
	'unicode-bidi',
	'vertical-align',
	'visibility',
	'white-space',
	'widows',
	'word-spacing',
	
	'font',
	'font-family',
	'font-size',
	'font-style',
	'font-variant',
	'font-weight',
	'line-height',

	'border',
	'border-bottom',
	'border-bottom-color',
	'border-bottom-style',
	'border-bottom-width',
	'border-collapse',
	'border-color',
	'border-left',
	'border-left-color',
	'border-left-style',
	'border-left-width',
	'border-right',
	'border-right-color',
	'border-right-style',
	'border-right-width',
	'border-spacing',
	'border-style',
	
	'border-top',
	'border-top-color',
	'border-top-style',
	'border-top-width',
	'border-width',
	
	'-moz-border-radius',
	'-webkit-border-radius',
	'-khtml-border-radius',
	'border-radius',
	
	'outline',
	'outline-color',
	'outline-style',
	'outline-width',
	
	'color',
	
	'background',
	'background-attachment',  		
	'background-color',
	'background-image',
	'background-position',
	'background-repeat',
	
	'-webkit-background-size',
	'-moz-background-size',
	'background-size',
	
	'-webkit-background-clip',
	'-moz-background-clip',
	'background-clip',
	
	'-webkit-background-origin',
	'-moz-background-origin',
	'background-origin',
	
	'-moz-box-shadow',
	'-webkit-box-shadow',
	'box-shadow',
	
	'-webkit-transition',
	'-moz-transition',
	'-o-transition',
	'transition',
	
	'-moz-user-select',
	'-webkit-user-select',
	'user-select',

	'-moz-user-drag',
	'-webkit-user-drag',
	'user-drag',
	
	'-moz-box-align',
	'-webkit-box-align',
	'-ms-box-align',
	'box-align',
	
	'-moz-box-pack',
	'-webkit-box-pack',
	'-ms-box-pack',
	'box-pack',
	
	'-moz-box-sizing',
	'-webkit-box-sizing',
	' box-sizing',

);
